//
//  PupilData.swift
//  TimeTable
//
//  Created by Alexander Gertsch on 24.12.21.
//

import Foundation

struct PupilData {
    // In the pupilDefinitions-array,
    // every Pupil has its own data-entry.
    // The entry's structure is shown at the top.
    
    static let pupilDefinitions: [(
        lastName: String,
        firstName: String,
        sex: Sex,
        promotion: Promotion,
        focus: Focus?,
        instruments: [(subject: Subject, teacher: TeacherData.id, duration: Lesson.Duration)],
        frees: [Subject]
    )] = [
        
        // MARK: - promotion 153a
        ("Berger", "Erin", .w, .p153a, nil, [(.sax,.VM,.full)], []),
        ("Bergkraut", "Orell", .m, .p153a, nil, [(.vl,.EO,.half)], [.FFPolit]),
        ("Bollag", "Ella", .w, .p153a, nil, [(.voc,.IA,.full)], []),
        ("Cal", "Stella", .w, .p153a, nil, [(.p,.AG,.half)], []),
        ("Dardel", "Mattia", .m, .p153a, nil, [(.git,.AW,.full)], []),
        ("Duccheschi", "Joya", .w, .p153a, nil, [(.p,.AG,.full)], []),
        ("Kempf", "Ella", .w, .p153a, nil, [(.git,.HPZ,.full)], [.FFPolit]),
        ("Leuenberger", "Ivo", .m, .p153a, nil, [(.p,.AG,.full)], []),
        ("Meienberg", "Nora", .w, .p153a, nil, [(.git,.AW,.half)], []),
        ("Müller", "Olivia", .w, .p153a, nil, [(.voc,.KMK,.full)], []),
        ("Ohle", "Franziska", .w, .p153a, nil, [(.voc,.LeK,.full)], []),
        ("Pellicioli", "Alessandro", .m, .p153a, nil, [(.p,.SdT,.full)], []),
        ("Schär", "Yangzom", .w, .p153a, nil, [(.vc,.RM,.half),(.voc,.LeK,.half)], [.FFPolit]),
        ("Snedecker", "Mea", .w, .p153a, nil, [(.p,.AG,.half)], []),
        ("Stamm", "Mia", .w, .p153a, nil, [(.p,.SdT,.full)], []),
        ("Stevens", "Eva", .w, .p153a, nil, [(.git,.HPZ,.full)], []),
        ("Syz", "Henry", .m, .p153a, nil, [(.p,.AFu,.full)], []),
        ("Temnenko", "Sofia", .w, .p153a, nil, [(.vl,.EO,.full)], []),
        ("Vernier", "Charlotte", .w, .p153a, nil, [(.p,.SiS,.full)], []),
        ("Züst", "Luis", .m, .p153a, nil, [(.voc,.IA,.full)], []),
        
        // MARK: - promotion 153b
        ("Arnold", "Constantin", .m, .p153b, nil, [(.dr,.ext,.unknown)], []),
        ("Boendermaker", "Lynn", .w, .p153b, nil, [(.vl,.EO,.half)], []),
        ("Bressan", "Nelly", .w, .p153b, nil, [(.p,.SdT,.half)], []),
        ("Dufner", "Anne", .w, .p153b, nil, [(.p,.AG,.half)], []),
        ("Endtinger", "Mailin", .w, .p153b, nil, [(.voc,.IA,.half)], []),
        ("Gonçalves de Oliveira", "Gabriel", .m, .p153b, nil, [(.git,.AW,.full)], []),
        ("Greuter", "Olivia", .w, .p153b, nil, [(.p,.AG,.half)], [.FFSalsa]),
        ("Händel", "Smilla", .w, .p153b, nil, [(.git,.HPZ,.full)], []),
        ("Hardmeier", "Klara", .w, .p153b, nil, [(.harp,.JB,.half),(.voc,.IA,.half)], []),
        ("Heuer", "Jeanne", .w, .p153b, nil, [(.voc,.IA,.half)], []),
        ("Kempter", "Elin", .w, .p153b, nil, [(.p,.SdT,.half)], []),
        ("Lutz", "Neo", .m, .p153b, nil, [(.p,.SdT,.full)], []),
        ("Michel", "Simone", .w, .p153b, nil, [(.voc,.LeK,.full)], [.FFSalsa]),
        ("Muamba", "Joël", .m, .p153b, nil, [(.voc,.KMK,.full)], []),
        ("Rashidi", "Puriya", .m, .p153b, nil, [(.git,.HPZ,.full)], []),
        ("Rowling", "Lars", .m, .p153b, nil, [(.p,.AG,.full)], []),
        ("Siciliano", "Hannah", .w, .p153b, nil, [(.p,.AG,.half)], []),
        ("Städeli", "Aurel", .m, .p153b, nil, [(.p,.SiS,.half)], []),
        ("Stecher", "Annatina", .w, .p153b, nil, [(.p,.AFu,.full)], []),
        ("Tiemer", "Leni", .w, .p153b, nil, [(.p,.AG,.full)], []),
        
        // MARK: - promotion 153c
        ("Amon", "Maximilian", .m, .p153c, .nw, [], []),
        ("Fernandes", "Leandro", .m, .p153c, .nw, [], []),
        ("Fries", "Lena", .w, .p153c, .nw, [], []),
        ("Gasser", "Lukas", .m, .p153c, .nw, [], []),
        ("Ghebrelul", "Mikal", .w, .p153c, .nw, [], []),
        ("Gruber", "Carlos", .m, .p153c, .nw, [], []),
        ("Hanania", "James", .m, .p153c, .nw, [], []),
        ("Harsch", "Celina", .w, .p153c, .nw, [], []),
        ("Ineke", "Charles", .m, .p153c, .nw, [], []),
        ("Largiadèr", "Nauel", .m, .p153c, .nw, [], []),
        ("Roth", "Lucas", .m, .p153c, .nw, [], []),
        ("Schaer", "Flurin", .m, .p153c, .nw, [], []),
        ("Schneiter", "Ronja", .m, .p153c, .nw, [], []),
        ("Schwarz", "Andrin", .m, .p153c, .nw, [], []),
        ("Tabche", "Jasmin", .w, .p153c, .nw, [], []),
        ("Totaro", "Felipe", .m, .p153c, .nw, [], []),
        ("Untersander", "Timo", .m, .p153c, .nw, [], []),
        ("Wirth", "Nils", .m, .p153c, .nw, [], []),
        ("Zhelyazkov", "Christo", .m, .p153c, .nw, [], []),
        ("Zweifel", "Moritz", .m, .p153c, .nw, [], []),
        
        // MARK: - promotion 152a
        ("Bidermann", "Elina", .w, .p152a, .bg, [(.vl,.EO,.half)], []),
        ("Brügger", "Silvan", .m, .p152a, .ppp, [], []),
        ("Büttler", "Till", .m, .p152a, .bg, [(.voc,.LeK,.half)], []),
        ("Campell", "Seraina Nina", .w, .p152a, .mu, [(.harp,.JB,.half)], []),
        ("Domeisen", "Lucian Jasper", .m, .p152a, .bg, [(.git,.AW,.half)], []),
        ("Gisler", "Ina", .w, .p152a, .ppp, [], []),
        ("Graullera Castro", "Sara", .w, .p152a, .ppp, [(.vl,.EO,.half),(.voc,.LeK,.half)], []),
        ("Grommé", "Samuel", .m, .p152a, .mu, [(.p,.AG,.half)], []),
        ("Hardmeier", "Julia", .w, .p152a, .ppp, [], []),
        ("Heierle", "Fabienne", .w, .p152a, .ppp, [], []),
        ("Hesse", "Emanuel", .m, .p152a, .bg, [(.p,.SiS,.half)], []),
        ("Imesch", "Dominic", .m, .p152a, .ppp, [(.voc,.IA,.half)], []),
        ("Ingold", "Chiara", .w, .p152a, .mu, [(.cl,.DJ,.full),(.p,.SdT,.half)], []),
        ("Koch", "Valérie", .w, .p152a, .ppp, [(.git,.AW,.half)], [.FFSalsa]),
        ("Liechti", "Leonie", .w, .p152a, .bg, [(.git,.HPZ,.half)], []),
        ("Liechti", "Mary", .w, .p152a, .bg, [(.git,.HPZ,.half),(.p,.AFu,.half)], []),
        ("Lüthy", "Hannah", .w, .p152a, .mu, [(.voc,.IA,.half),(.p,.AG,.half)], [.FFSalsa]),
        ("Rom", "Lia", .w, .p152a, .mu, [(.git,.AW,.full),(.voc,.IA,.half)], []),
        ("Rötheli", "Paula", .w, .p152a, .ppp, [(.qfl,.SSO,.half)], [.FFSalsa]),
        ("Safari", "Farzaneh", .w, .p152a, .bg, [(.p,.SdT,.half)], []),
        ("Seeholzer", "Yves", .m, .p152a, .bg, [(.voc,.LeK,.full)], []),
        ("Sowe", "Yacine", .w, .p152a, .bg, [(.p,.AFu,.half)], []),
        ("Stuebi", "Charlotte", .w, .p152a, .bg, [(.p,.AFu,.half)], []),
        ("Waeber", "Naomi", .w, .p152a, .mu, [(.p,.SdT,.full)], []),
        ("Wildberger", "Chet", .m, .p152a, .ppp, [(.p,.SiS,.full)], []),
        
        // MARK: - promotion 152b
        ("Alder", "Aline", .w, .p152b, .ppp, [], []),
        ("Bauer", "Chiara", .w, .p152b, .ppp, [], []),
        ("Bünter", "René", .m, .p152b, .ppp, [(.tp,.GN,.half)], [.FFPolit]),
        ("Chanthakumar", "Yanuja", .w, .p152b, .ppp, [], []),
        ("Damaro", "Nora", .w, .p152b, .ppp, [], []),
        ("Domeisen", "Constantine", .w, .p152b, .bg, [(.p,.AG,.half)], [.FFAstro]),
        ("Freitag", "Konstantin", .m, .p152b, .ppp, [], []),
        ("Frischknecht", "Nina", .w, .p152b, .bg, [(.hrn,.ext,.unknown)], []),
        ("Gadient", "Pablo", .m, .p152b, .bg, [(.vc,.RM,.half),(.voc,.KMK,.half)], []),
        ("Haemmerli", "Lea", .w, .p152b, .ppp, [], []),
        ("Harsch", "Liv", .w, .p152b, .ppp, [], []),
        ("Haylock", "Mathilde", .w, .p152b, .mu, [(.voc,.IA,.full),(.p,.AG,.half)], []),
        ("Iff", "Lauriane", .w, .p152b, .ppp, [(.p,.AG,.half)], []),
        ("Knotz", "Lennox", .m, .p152b, .ppp, [(.p,.SiS,.half)], []),
        ("Laharpe", "Nicole", .w, .p152b, .ppp, [], []),
        ("Liechti", "Anny", .w, .p152b, .ppp, [], []),
        ("Meyer", "Ezra", .m, .p152b, .ppp, [(.git,.AW,.half)], [.FFSalsa]),
        ("Schmädecker", "Emma", .w, .p152b, .bg, [(.vc,.RM,.half)], []),
        ("Schneider", "Aurora", .w, .p152b, .bg, [(.p,.SdT,.half)], []),
        ("Stüssi", "Caroline", .w, .p152b, .mu, [(.bfl,.ext,.unknown)], []),
        ("Vaid", "Shirin", .w, .p152b, .bg, [(.voc,.KMK,.half)], [.FFAstro]),
        ("Wenk", "Arissa", .w, .p152b, .ppp, [(.p,.SiS,.half)], []),
        ("Winkler", "Jasmin", .w, .p152b, .mu, [(.voc,.LeK,.full),(.qfl,.SSO,.half)], []),
        
        // MARK: - promotion 152c
        ("Arnautovic", "Hussein", .m, .p152c, .nw, [], []),
        ("Baier", "Bruno", .m, .p152c, .nw, [], []),
        ("Ben Atigue", "Finn", .m, .p152c, .nw, [], []),
        ("Bogus", "Rabia", .w, .p152c, .nw, [], []),
        ("Bruggesser", "Lorin", .m, .p152c, .nw, [], []),
        ("Demoz", "Zelalem", .m, .p152c, .nw, [], [.FFAstro]),
        ("Doldt", "Sebastian", .m, .p152c, .nw, [], [.FFAstro]),
        ("Gruber", "Tom", .m, .p152c, .nw, [], []),
        ("Hardmeier", "Noah", .m, .p152c, .nw, [], []),
        ("Hüffer", "Alexander", .m, .p152c, .nw, [], [.FFAstro]),
        ("Joos", "Florian", .m, .p152c, .nw, [(.git,.AW,.half)], [.FFAstro]),
        ("Kiener", "Sasha", .m, .p152c, .nw, [], []),
        ("Rijk", "Veronica", .w, .p152c, .nw, [], []),
        ("Schlatter", "Kaya", .w, .p152c, .nw, [], []),
        ("Schürmann", "Thomas", .m, .p152c, .nw, [], []),
        ("Sidler", "Lea", .w, .p152c, .nw, [], []),
        ("Sigrist", "Jakob", .m, .p152c, .nw, [], [.FFAstro]),
        ("Soares Matos", "Lara", .w, .p152c, .nw, [], []),
        ("Ullmann", "Basil", .m, .p152c, .nw, [], [.FFAstro]),
        ("Varnakumaran", "Branahy", .w, .p152c, .nw, [], []),
        
        // MARK: - promotion 151a
        ("Baumgartner", "Minea", .w, .p151a, .mu, [(.p,.AG,.half)], []),
        ("Boesch", "Carla", .w, .p151a, .mu, [(.cl,.DJ,.full)], [.FFPolit,.FFSalsa]),
        ("Bollinger", "Yannick", .m, .p151a, .ppp, [(.voc,.IA,.half)], [.FFWeb]),
        ("Ducommun", "Rebecca", .w, .p151a, .mu, [(.p,.SiS,.full)], []),
        ("Galladé", "Amélie", .w, .p151a, .ppp, [(.p,.AG,.half)], [.FFPolit]),
        ("Gerlacher", "Alisa", .w, .p151a, .ppp, [], []),
        ("Häring", "Jana Lilian", .w, .p151a, .mu, [(.voc,.IA,.half),(.harp,.JB,.half)], []),
        ("Hug", "Elin", .w, .p151a, .ppp, [], []),
        ("Jaggi", "Maxime", .w, .p151a, .bg, [(.p,.SdT,.half)], []),
        ("Kärcher", "Kaspar", .m, .p151a, .bg, [(.git,.HPZ,.half)], []),
        ("Kormann", "Lina", .w, .p151a, .bg, [(.voc,.IA,.half)], []),
        ("Lauener", "Noel", .m, .p151a, .bg, [(.p,.AG,.half)], []),
        ("Meienberg", "Simon", .m, .p151a, .ppp, [], []),
        ("Miljko", "Mia", .w, .p151a, .mu, [(.voc,.KMK,.half),(.p,.SiS,.half)], []),
        ("Mundt", "Lorenz", .m, .p151a, .ppp, [], []),
        ("Reichmuth Lopez", "Amber", .w, .p151a, .ppp, [], []),
        ("Sartoretti", "Eva", .w, .p151a, .mu, [(.voc,.KMK,.half)], []),
        ("Schiesser", "Colin", .m, .p151a, .bg, [(.sax,.VM,.half)], []),
        ("Usenbenz", "Joscha", .m, .p151a, .bg, [(.dr,.ext,.unknown)], []),
        
        // MARK: - Promotion 151b
        ("Balsiger", "Julian", .m, .p151b, .bg, [(.dr,.ext,.unknown)], []),
        ("Bandle", "Sophie", .w, .p151b, .mu, [(.tp,.GN,.full)], []),
        ("Bleiker", "Michael", .m, .p151b, .bg, [(.git,.HPZ,.full)], []),
        ("De Plecker", "Paulina", .w, .p151b, .mu, [(.vc,.RM,.full)], []),
        ("Döseme", "Ezo Cansin", .w, .p151b, .ppp, [(.git,.AW,.half)], []),
        ("Hofmann", "Anna", .w, .p151b, .bg, [(.voc,.IA,.full)], []),
        // ("Kampwirth", "Joyce", .w, .p151b, .ppp, [(.voc,.LeK,.ganz)], []),
        ("Karrer", "Jodok", .m, .p151b, .mu, [(.voc,.KMK,.full),(.p,.AFu,.half)], []),
        ("Lambert", "Max", .m, .p151b, .bg, [(.p,.AFu,.half)], []),
        ("Leuzinger", "Philippe", .m, .p151b, .mu, [(.dr,.ext,.unknown),(.p,.AG,.half)], []),
        ("Pernet", "Hannah", .w, .p151b, .ppp, [(.p,.SiS,.half)], []),
        ("Piko", "Lili", .w, .p151b, .mu, [(.p,.SdT,.full)], []),
        ("Rüschen", "Isabella", .w, .p151b, .ppp, [], []),
        ("Shah Mardi", "Furuzan", .w, .p151b, .bg, [(.p,.SiS,.half)], []),
        ("Sohm", "Annika", .w, .p151b, .ppp, [(.voc,.IA,.half)], []),
        ("Strässler", "Annika", .w, .p151b, .bg, [(.cl,.DJ,.full)], [.FFAstro]),
        ("von Büren", "Anja Luna", .w, .p151b, .bg, [(.git,.HPZ,.full)], []),
        ("Walser", "Dora Leina", .w, .p151b, .bg, [(.p,.AG,.full)], []),
        
        // MARK: - Promotion 151c
        ("Battaglia", "Zoe", .w, .p151c, .nw, [], []),
        ("Bertolin", "Michel", .m, .p151c, .nw, [], [.FFPolit]),
        ("Brügger", "Mauro", .m, .p151c, .nw, [], [.FFAstro]),
        ("Echsle", "Tizian", .m, .p151c, .nw, [], [.FFWeb]),
        ("Ganija", "Pajazit", .m, .p151c, .nw, [], []),
        ("Gisler", "Jeanne", .w, .p151c, .nw, [], []),
        ("Kunszt", "Magor", .m, .p151c, .nw, [], []),
        ("Lang", "Gwendolyn", .w, .p151c, .nw, [(.p,.AFu,.half)], []),
        ("Meng", "Romy Lou", .w, .p151c, .nw, [], []),
        ("Pfister", "Rémy", .m, .p151c, .nw, [], []),
        ("Regnani", "Franco", .m, .p151c, .nw, [], [.FFPolit]),
        ("Riedel", "Charlotte", .w, .p151c, .nw, [], [.FFAstro]),
        ("Tedaldi", "Michel", .m, .p151c, .nw, [], [.FFWeb]),
        ("Thür", "Iria", .w, .p151c, .nw, [(.voc,.LeK, .full)], []),
        ("Zürrer", "Laurens", .m, .p151c, .nw, [], []),
        
        // MARK: - Promotion 150a
        ("Allemann", "Lucie", .w, .p150a, .ppp, [(.git,.AW,.half)], []),
        ("Binswanger", "Milena", .w, .p150a, .mu, [(.voc,.LeK,.full)], []),
        ("Blickenstorfer", "Enna", .w, .p150a, .bg, [], []),
        ("Bott", "Helene", .w, .p150a, .bg, [(.voc,.IA,.half)], []),
        ("Ducret", "Eugénie", .w, .p150a, .bg, [], []),
        ("Gross", "Carleen", .w, .p150a, .bg, [(.voc,.LeK,.half)], []),
        ("Lalkaka", "Thara", .w, .p150a, .mu, [(.p,.AG,.full)], []),
        ("Lilburn", "Kimberley", .w, .p150a, .ppp, [], []),
        ("Lusch", "Hannah", .w, .p150a, .ppp, [(.p,.AG,.half)], []),
        ("Muamba", "Naomi", .w, .p150a, .bg, [], []),
        ("Ninnis", "Melina", .w, .p150a, .ppp, [], []),
        ("Pfiffner", "Olivia", .w, .p150a, .mu, [(.git,.HPZ,.full)], []),
        ("Pini", "Marialuna", .w, .p150a, .ppp, [(.git,.HPZ,.half)], []),
        ("Platz", "Ursina", .w, .p150a, .mu, [(.vl,.EO,.full)], []),
        ("Radivojevic", "Nina", .w, .p150a, .ppp, [], []),
        ("Schmid", "Ladina", .w, .p150a, .ppp, [(.p,.AG,.half)], []),
        ("Stuppöck", "Jill", .w, .p150a, .ppp, [], []),
        ("von Koss", "Katharina", .w, .p150a, .bg, [(.p,.AG,.half)], []),
        ("Widmer", "Joelle", .w, .p150a, .ppp, [(.git,.AW,.half)], []),
        ("Widmer", "Meret", .w, .p150a, .bg, [(.voc,.IA,.half)], []),
        
        // MARK: - Promotion 150b
        ("Aebi", "Celia", .w, .p150b, .bg, [(.vc,.RM,.half)], []),
        ("Bregy", "Andrj", .m, .p150b, .ppp, [], []),
        ("Cavelti", "Sina", .w, .p150b, .mu, [(.p,.AG,.full)], []),
        ("De Martiis", "Zeno", .m, .p150b, .bg, [], []),
        ("Domeisen", "Amadeus", .m, .p150b, .bg, [], []),
        ("Ducret", "Ann", .w, .p150b, .ppp, [], []),
        ("Duran", "Dylan", .m, .p150b, .mu, [(.p,.AFu,.full)], []),
        ("Eser", "Basil", .m, .p150b, .ppp, [], []),
        ("Fazili", "Urya", .w, .p150b, .ppp, [], []),
        ("Forster", "Elija", .m, .p150b, .ppp, [], []),
        ("Ghukasyan", "Ani", .w, .p150b, .mu, [(.voc,.IA,.full)], []),
        ("Herold", "Maurus", .m, .p150b, .ppp, [], []),
        ("Landtwing", "Jonathan", .m, .p150b, .mu, [(.dr,.ext,.full),(.p,.AG,.half)], []),
        ("Locher", "Janis", .m, .p150b, .bg, [], []),
        ("Paravac", "Mascha", .w, .p150b, .bg, [], []),
        ("Rötheli", "Felix", .m, .p150b, .ppp, [], []),
        ("Ruf", "Melina", .w, .p150b, .ppp, [], []),
        ("Sauter", "Norea", .w, .p150b, .bg, [(.voc,.KMK,.half)], []),
        ("Schmidt", "Indira", .w, .p150b, .ppp, [(.voc,.KMK,.half)], []),
        ("Senn", "Nicolas", .m, .p150b, .mu, [(.voc,.IA,.full)], []),
        ("Stamm", "Max", .m, .p150b, .bg, [(.git,.AW,.half)], []),
        ("Wieser", "Sophie", .w, .p150b, .mu, [(.p,.AG,.full)], []),
        ("Willer", "Nicolas", .m, .p150b, .mu, [(.git,.AW,.full)], []),
        
        // MARK: - Promotion 150c
        ("Bischof", "Lukas", .m, .p150c, .nw, [], []),
        ("Budliger", "Julian", .m, .p150c, .nw, [(.p,.AG,.half)], []),
        ("Carle", "Nicolo", .m, .p150c, .nw, [], [.FFPolit]),
        ("Dietrich", "Ella", .w, .p150c, .nw, [(.p,.SiS,.half)], [.FFWeb]),
        ("Eckhardt", "Maximilian", .m, .p150c,  .nw, [], []),
        ("Ehrat", "Lou", .m, .p150c, .nw, [], []),
        ("Graullera Castro", "Annika", .w, .p150c, .nw, [], [.FFSalsa]),
        ("Hammer", "Florian", .m, .p150c, .nw, [], []),
        ("Hüsser", "Moritz", .m, .p150c, .nw, [], []),
        ("Kazakov", "Timofej", .m, .p150c, .nw, [], []),
        ("Petitjean", "Yves", .m, .p150c, .nw, [(.sax,.VM,.half)], []),
        ("Potsis", "Ioannis", .m, .p150c, .nw, [], []),
        ("Regli", "Flurin", .m, .p150c, .nw, [], []),
        ("Rigolini", "Alessandro", .m, .p150c, .nw, [], []),
        ("Sahiner", "Sila", .w, .p150c, .nw, [], [.FFWeb]),
        ("Schmid", "Mario", .m, .p150c, .nw, [(.p,.AG,.half)], [.FFWeb]),
        ("Schwarzenbach", "Alec", .m, .p150c, .nw, [(.p,.AG, .half)], []),
        ("Sieger", "Julia", .w, .p150c, .nw, [], []),
        ("Söllner", "Falco", .m, .p150c, .nw, [(.git,.HPZ,.half)], []),
        ("Sotzek", "Hannah", .w, .p150c, .nw, [], [])
    ]
}
